name: Python CI

on:
  push:
    branches: [main, tests_adding]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock pyvis neo4j pyinstaller

      - name: Run unit/mocked tests
        run: |
          pytest tests/ -q --tb=short

  build-exe:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pyvis

      - name: Build executable with PyInstaller
        run: |
          pyinstaller neo4j_pyqt_app.spec --clean --noconfirm

      - name: Verify PyVis templates included
        run: |
          $exe_path = ".\dist\Neo4jPyQtApp\pyvis\templates\template.html"
          if (-Not (Test-Path $exe_path)) { 
            Write-Error "template.html not found in the built exe!" 
          } else { 
            Write-Host "template.html found ✅"
          }
